# tf_step_config.yml
name: tf_step_config

on:
  workflow_call:
    inputs:
      #Runner
      runner:
        required: false
        type: string
        default: 'ubuntu-latest'
        description: 'Either the type of runner or the label of the self hosted runner to be used. Defaults to ubuntu-latest.'

      #Terraform Infra Repository
      infra_repo:
        required: true
        type: string
        description: 'Name of the Terraform Infra Repository where HCL code resides.'

      infra_repo_ref:
        required: false
        type: string
        default: main
        description: 'The branch, tag or commit SHA to checkout. Defaults to main.'

      #Terraform Config Repository
      config_repo:
        required: true
        type: string
        description: 'Name of the Terraform Config Repository where JSON configurations resides.'

      config_repo_ref:
        required: false
        type: string
        default: main
        description: 'The branch, tag or commit SHA to checkout. Defaults to main.'

      #Terraform Configuration
      config_directory:
        required: true
        type: string
        description: 'The path to the configuration relative to infra-repo/config, infra-repo/config_override, infra-repo/terraform and config-repo/config directories. The same path should exist at all locations for configurations properly parsed.'

      #GitHub Owner
      github_owner:
        required: true
        type: string
        description: 'Either the GitHub username or organization name.'

    secrets:
      #GitHub PAT
      github_pat:
        required: true

jobs:
  tf_step_config:
    runs-on: ${{ inputs.runner }}
    steps:
      - name: Clean runner workspace
        run: |
          shopt -s dotglob
          rm -rf "${GITHUB_WORKSPACE:?}/*"
        shell: bash

      - name: Set GitHub environment variables
        run: |
          echo "GITHUB_TOKEN=${{ secrets.github_pat }}" >> $GITHUB_ENV
          echo "GITHUB_OWNER=${{ inputs.github_owner }}" >> $GITHUB_ENV

      - name: Install tree and display directory structure
        run: |
          if ! command -v tree &> /dev/null; then
            sudo apt-get update
            sudo apt-get install -y tree
          fi

          echo "Displaying tree structure of the workspace:"
          workspace="${{ github.workspace }}"
          tree "${workspace}" -L 5 -h
        shell: bash

      - name: Checkout infra repository
        uses: actions/checkout@v4
        with:
          repository: ${{ inputs.github_owner }}/${{ inputs.infra_repo }}
          ref: ${{ inputs.infra_repo_ref}}
          token: ${{ secrets.github_pat }}
          path: infra-repo

      - name: Checkout config repository
        uses: actions/checkout@v4
        with:
          repository: ${{ inputs.github_owner }}/${{ inputs.config_repo }}
          ref: ${{ inputs.config_repo_ref}}
          token: ${{ secrets.github_pat }}
          path: config-repo

      - name: After tree
        run: |
          echo "Displaying tree structure of the workspace:"
          workspace="${{ github.workspace }}"
          tree "${workspace}" -L 5 -h
        shell: bash

      - name: List files in directories
        run: |
          workspace="${{ github.workspace }}"
          config_directory="${{ inputs.config_directory }}"

          override_directory="${workspace}/infra-repo/config_override/${config_directory}"
          echo "Listing files in override directory:"
          ls -lha "${override_directory}" || true

          config_config_directory="${workspace}/config-repo/config/${config_directory}"
          echo "Listing files in config config directory:"
          ls -lha "${config_config_directory}" || true

          infra_config_directory="${workspace}/infra-repo/config/${config_directory}"
          echo "Listing files in infra config directory:"
          ls -lha "${infra_config_directory}" || true
        shell: bash

      - name: Set up Python
        uses: actions/setup-python@v5

      - name: Set up a Python virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate
          python -m pip install --upgrade pip
          pip install jsonmerge

      - name: Merge and Validate JSON configurations
        run: |
          import json
          import os
          from glob import glob
          from jsonmerge import merge

          # Get workflow inputs
          config_directory = '${{ inputs.config_directory }}'
          print(f"Config directory: {config_directory}")
          workspace = os.getenv('GITHUB_WORKSPACE')

          # Helper function to load and validate JSON configuration
          def load_json(pattern):
              configs = []
              for file_path in glob(pattern, recursive=True):
                  print(f"Found JSON file: {file_path}")
                  try:
                      with open(file_path, 'r') as f:
                          config = json.load(f)
                          configs.append(config)
                          print(f"Loaded JSON configuration from {file_path}: {config}")
                  except json.JSONDecodeError as e:
                      print(f"JSON syntax error in {file_path}: {e}")
                      exit(1)
              return configs

          # Paths to JSON file patterns
          override_pattern = os.path.join(workspace, 'infra', 'config_override', config_directory, '*.json')
          config_pattern = os.path.join(workspace, 'config', 'config', config_directory, '*.json')
          local_pattern = os.path.join(workspace, 'infra', 'config', config_directory, '*.json')

          print(f"Override pattern: {override_pattern}")
          print(f"Config pattern: {config_pattern}")
          print(f"Local pattern: {local_pattern}")

          # Load and validate configurations
          local_configs = load_json(local_pattern)
          configs = load_json(config_pattern)
          override_configs = load_json(override_pattern)

          # Merge configurations
          merged_config = {}
          for config in local_configs + configs + override_configs:
              merged_config = merge(merged_config, config)
          print(f"Merged configuration: {merged_config}")

          # Write terraform.tfvars.json
          tfvars_path = os.path.join(os.environ['GITHUB_WORKSPACE'], 'terraform.tfvars.json')
          with open(tfvars_path, 'w') as f:
              json.dump(merged_config, f, indent=2)

          print(f"Terraform variables have been written to {tfvars_path}")
        shell: python

      - name: Upload terraform.tfvars.json as artifact
        uses: actions/upload-artifact@v4
        with:
          name: terraform-tfvars
          path: ${{ github.workspace }}/terraform.tfvars.json